#!/usr/bin/env bash

HOSTNAME=$(hostname)
MACHINE="${HOSTNAME}"

if [ ! "x""${1}" == "x" ]; then
  MACHINE="${1}"
fi

if [[ ! -e "machines/${MACHINE}/base.nix" ]]; then
  echo "Missing machines/${MACHINE}/base.nix" >&2
  exit 1
fi
if [[ ! -e "machines/${MACHINE}/full.nix" ]]; then
  echo "Missing machines/${MACHINE}/full.nix" >&2
  exit 1
fi

dirName="$(dirname "${0}")"

outputDir="$(nix-build --no-out-link -E '
  with import <nixpkgs> {};

  callPackage (import '"${dirName}"'/ln-host.nix {
    machine = "'"${MACHINE}"'";
  }) {}
')"
configBuildStatus="${?}"

if [ "${configBuildStatus}" -ne 0 ]; then
  echo "Failed to build config options" >&2
  exit 2
fi

cp --no-preserve=all "${outputDir}/base.nix" base.nix
cp --no-preserve=all "${outputDir}/full.nix" full.nix

# Pick full by default
cp full.nix configuration.nix
