#!/usr/bin/env bash

HOSTNAME=$(hostname)
MACHINE="$HOSTNAME"

if [ ! "x""$1" == "x" ]; then
  MACHINE="$1"
fi

if [[ ! -e "machines/$MACHINE/configuration.nix" ]]; then
  echo "Missing machines/$MACHINE/configuration.nix" >&2
  exit 1
fi

cat <<EOF | tee > configuration.nix
{ ...
}:

{
	imports = [
		./machines/$MACHINE/configuration.nix
	];
}
EOF

